promocode/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index', views.index, name='index'),
    path('', views.add_order, name='get_user_data'),
    path('add_code', views.add_code, name='add_code'),
    # get coupon or order_amount'''

    path('get_code', views.get_code, name='get_code'),
    path('add_coupon_order', views.add_coupon_order, name='add_coupon_order'),
    path('edit_coupon/<int:id>', views.edit_coupon, name='edit_coupon'),
    path('delcoupon/<int:id>', views.delcoupon, name='delcoupon')
]

promocode/promocode/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

promocode/myapp/models.py
from django.db import models
from datetime import date
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
# from testapp.core.models import User
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.utils import timezone
from django.conf import settings

User = settings.AUTH_USER_MODEL

# Create your models here.

DISCOUNT_CHOICES = (("percentage", "Percentage"), ("flat", "Flat"))
GENDER_CHOICES = (("m", "Male"), ("f", "Female"))


class Coupon(models.Model):

    def validate_date(value):
        v = timezone.now()
        if value < v:
            raise ValidationError("please don't enter a pastdate")

    def validate_start(start):

        d = timezone.now()
        if start > d:
            raise ValidationError("enter valid date ")

    # def clean(self):
    #     cleaned_data = super().clean()
    #     start_date = cleaned_data.get("start_date")
    #     expiration_date = cleaned_data.get("end_date")
    #     if expiration_date < start_date:
    #         raise ValidationError("End date should be greater than start date.")

    code = models.CharField(
        max_length=6,
        unique=True,
        # help_text="Only uppercase letters & numbers are allowed.",
        validators=[
            RegexValidator(
                "^[A-Z0-9]*$", "Only uppercase letters & numbers are allowed.",

            )
        ],
    )

    # gender = models.CharField(max_length=6, choices=GENDER_CHOICES)

    start_date = models.DateTimeField(validators=[validate_start], null=True, blank=True)
    expiration_date = models.DateTimeField(validators=[validate_date], null=True, blank=True)
    discount_type = models.CharField(max_length=10, choices=DISCOUNT_CHOICES)
    discount = models.PositiveIntegerField()
    number_of_uses = models.PositiveIntegerField(
        # help_text="How many times this coupon will be used.", default=1
    )

    per_user_limit = models.PositiveIntegerField()
    textfile=models.CharField(max_length=10,blank=True)

    # is_active = models.BooleanField(default=True)

    # is_used = models.BooleanField(default=False)

    def __str__(self):
        return self.code

    def __enumerable_to_display(self, enumerables, enum_value):
        """Get the human readable value from an enumerable list of key-value pairs."""
        return dict(enumerables)[enum_value]

    # @property
    # def display_gender(self):
    #     """
    #     return coupon gender
    #     """
    #     return self.__enumerable_to_display(GENDER_CHOICES, self.gender)


class Userprofile(AbstractUser):
    date_of_birth = models.DateField(blank=False, null=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)

    def __str__(self):
        return "{}".format(self.username)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_related')
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE, related_name='coupon_related')
    order_amount = models.IntegerField(validators=[MinValueValidator(100), MaxValueValidator(150000)])
    total_amount = models.PositiveIntegerField(
        # help_text="Order total amount after code redemption applied."
    )

    def __str__(self):
        return "{} - {}".format(self.user.username, self.coupon.code)

    @property
    def discount_amout(self):
        """
        return coupon gender
        """

        return self.order_amount - self.total_amount

promocode/myapp/forms.py
from django import forms
from .models import *


class CouponApplyForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = "__all__"

promocode/myapp/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
import datetime


# Create your views here.

def index(request):
    return HttpResponse("hello")


def get_code(request):
    """
    Return all code with all details.
    """

    codes = Coupon.objects.all()

    return render(
        request=request, template_name="codes.html", context={"codes": codes}
    )


# def get_all_order(request):
#     """
#     Return all code with all details.
#     """
#
#     codes = Order.objects.all()
#
#     return render(
#         request=request,
#         template_name="orders.html",
#         context={"codes": codes},
#     )


def add_code(request):
    """
    Add new Code form.
    """
    context = {}
    context["form"] = CouponApplyForm()

    if request.method == "POST":

        form = CouponApplyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("get_code"))
        else:
            context["form"] = form
            return render(request, "new_code.html", context)

    return render(request, "new_code.html", context)


def add_order(request):
    if request.method == "POST":
        coupon = request.POST.get('coupon')
        order_amount = int(request.POST.get('order_amount'))

        c = Coupon.objects.filter(code=request.POST.get('coupon')).first()  # 'c' is object of Coupon model

        user = Userprofile.objects.filter(date_of_birth=request.user.date_of_birth).first()

        if not c:
            return HttpResponse("Coupon not exists.")

        # user = request.user
        if c.discount_type == "flat":

            total_amount = order_amount - c.discount
        else:
            # import pdb;
            # pdb.set_trace()
            # birthdate = datetime.datetime.strftime(user.date_of_birth, "%d-%m")
            birthdate = user.date_of_birth

            today_date = datetime.date.today()
            valid_date = timezone.now().date().strftime("%m-%d")

            if birthdate and birthdate.strftime("%m-%d") == valid_date:
                discount = order_amount * (c.discount / 100)
                total = order_amount - discount
                total_amount = total - (total * 0.1)
            else:
                discount = order_amount * (c.discount / 100)
                total_amount = order_amount - discount

        try:

            max_limit = c.number_of_uses
            user_limit = c.per_user_limit

            if user.is_authenticated:
                user_count = len(Order.objects.filter(user=user, coupon=c))
                coupon_count = len(Order.objects.filter(coupon=c))

                # if max_limit < user_count:
                if coupon_count > user_limit:
                    return HttpResponse("Coupon limit is over")

                if user_count > max_limit:
                    return HttpResponse("Per user limit is over")

                new_order = Order.objects.create(coupon=c, order_amount=order_amount,
                                                 total_amount=total_amount, user=request.user)
                # new_order.save()
                # c.per_user_limit = c.per_user_limit - 1
                c.number_of_uses = c.number_of_uses - 1
                c.save()
                return HttpResponseRedirect('add_coupon_order')
            else:

                return HttpResponse("Coupon limit is over")
        except Exception as e:
            return HttpResponse(e.__str__())

            # new_order = Order.objects.create(coupon=c, order_amount=order_amount,
            #                                  total_amount=total_amount, user=request.user)
            # new_order.used += 1
            # new_order.save()

            # return HttpResponseRedirect('add_coupon_order')
    #     else:
    return render(request, "user_data.html")


# """
# Add User Details View.
# """
# context = {}
#
# if request.POST:
#     data = request.POST
#     order_amount = data.get("order_amount")
#     coupon = data.get("coupon")
#     # c = Coupon.objects.get(code=data.get('coupon'))  # 'c' is object of Coupon model
#     #
#     # user = Userprofile.objects.filter(date_of_birth=request.user.date_of_birth).first()
#
#     try:
#         # if User.objects.filter(id=user_id).exists():
#         #     user = User.objects.get(id=user_id)
#         #     profile, created = Userprofile.objects.get_or_create(user=user)
#         #     profile.date_of_birth = datetime.datetime.strptime(birthdate, "%m/%d/%Y")
#         #     profile.gender = gender
#         #     profile.save()
#         if not int(order_amount) in range(100, 1500000):
#             context["msg"] = "Order amount must be  between 100 to 1500001"
#
#         # redemption_msg = add_coupon_redemption(
#         # request.user, order_code, int(order_amount)
#         # )
#         # import pdb; pdb.set_trace()
#
#         if not Coupon.objects.filter(code=coupon).exists():
#             redemption_msg = "Coupon code does not exist."
#
#         coupon = Coupon.objects.get(code=coupon)
#
#         if (
#                 timezone.now() > coupon.start_date
#                 and timezone.now() < coupon.expiration_date
#         ):
#             if coupon.number_of_uses > 0:
#                 if len(coupon.objects.filter(coupon=coupon)) < coupon.per_user_limit:
#                     if coupon.discount_type == "percentage":
#                         discount_amout = (order_amount * coupon.discount) / 100
#                         amount = order_amount - discount_amout
#                         # Check Birthdate
#                         if timezone.now().date().strftime("%m/%d") == request.user.date_of_birth.strftime(
#                                 "%m/%d"):
#                             amount = amount - (amount * 10) / 100
#
#                         # if coupon.max_discount_amout < amount:
#                         #     amount = order_amount - coupon.max_discount_amout
#                     else:
#                         amount = order_amount - coupon.discount
#                     coupon.number_of_uses = coupon.number_of_uses - 1
#                     coupon.save()
#
#                     redemption_msg = "{username} is successfully applied this {coupon_code} coupon.".format(
#                         username=request.user.username,
#                         coupon_code=coupon.code
#                     )
#                 else:
#                     return render(request, "user_data.html", context)
#             else:
#                 redemption_msg = "Coupon code max limit used."
#         else:
#             redemption_msg = "Coupon code expiried or not activate yet."
#
#         context["msg"] = redemption_msg
#         return render(request, "user_data.html", context)
#         # else:
#         #     context["msg"] = "User ID does not exist."
#         #     return render(request, "user_data.html", context)
#     except Exception as e:
#         context["msg"] = e.__str__()
#         return render(request, "user_data.html", context)
#
# return render(request, "user_data.html", context)
#


def add_coupon_order(request):
    # coupon, order_amount):
    """
    add coupon info into order model
    """
    codes = Order.objects.all()

    return render(request, 'orders.html', {'codes': codes})


def edit_coupon(request, id):
    coupon = Coupon.objects.get(pk=id)
    order_count = coupon.coupon_related.filter().count()

    if request.method == "POST":
        form = CouponApplyForm(request.POST, instance=coupon)
        codes = request.POST.get('code')
        print(codes)

        if form.is_valid():
            if order_count:
                return HttpResponse("you can not change used coupon")
            else:
                coupon = codes
                form.save()
                return redirect('get_code')
        else:
            print(form.errors)
    else:
        form = CouponApplyForm(instance=coupon)
        context = {'coupon': coupon, 'form': form}
        return render(request, 'edit.html', context)


def delcoupon(request, id):
    coupon = Coupon.objects.get(pk=id)
    order_count = coupon.coupon_related.filter().count()

    if order_count:
        return HttpResponse("You can not delete used coupon")
    else:
        coupon.delete()
        return redirect('get_code')

promocode/myapp/templates/codes.html
<!DOCTYPE html>
<html>
<head>
    <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

    </style>
</head>
<body>

<h2 style="text-align: center;">Coupon Codes</h2>
<h2 style="text-align: left;">
    <a href="/add_code">
        Add Coupon
    </a>
</h2>

<table>
    <tr>
        <th>Code</th>

        <th>Gender</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Discount</th>
<!--        <th>is_active</th>-->

    </tr>
    {% for code in codes %}

    <tr>

        <td>{{code.code}}</td>
        <td>{{code.display_gender}}</td>
        <td>{{code.start_date}}</td>
        <td>{{code.expiration_date}}</td>
        <td>{{code.discount}}</td>
<!--        <td>{{code.is_active}}</td>-->

    </tr>
    {% endfor %}
</table>

</body>
</html>

promocode/myapp/templates/new_code.html
<!DOCTYPE html>
<html>
<body>

<h2 style="text-align: center;">Add New Coupon Code</h2>

<form action = "" method = "post" style="text-align: -webkit-center;">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#id_start_date" ).datepicker();
    $( "#id_expiration_date" ).datepicker();
  } );
  </script>

</body>
</html>

promocode/myapp/templates/orders.html
<!DOCTYPE html>
<html>
<head>
    <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

    </style>
</head>
<body>

<h2 style="text-align: center;">Coupon Order </h2>

<table>
    <tr>

        <th>Code</th>
        <th>Order Total Price</th>
        <th>Discount Price</th>
        <th>Order total amount (After Discount Applied)</th>
    </tr>
    {% for code in codes %}
    <tr>
        <td>{{code.user.username}}</td>
        <td>{{code.user.profile.date_of_birth}}</td>
        <td>
            {% if code.user.profile.gender == 'm' %}
            Male
            {% else %}
            Female
            {% endif %}
        </td>
        <td>{{code.coupon.code}}</td>
        <td>{{code.order_amount}}</td>
        <td>{{code.total_amount}}</td>
    </tr>
    {% endfor %}
</table>

</body>
</html>

promocode/myapp/templates/user_data.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid rgb(70, 68, 68);
  border-radius: 4px;
  resize: vertical;
}
input[type=email], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid rgb(70, 68, 68);
  border-radius: 4px;
  resize: vertical;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
}

input[type=submit] {
  background-color: rgb(37, 116, 161);
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: right;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}

.col-25 {
  float: left;
  width: 25%;
  margin-top: 6px;
}

.col-75 {
  float: left;
  width: 75%;
  margin-top: 6px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
</style>
</head>
<body>
<h2 style="text-align:center;">Order Data</h2>
<div class="container">

  <form action = " " method = "post" >
    {% csrf_token %}

    <div class="row">
        <div class="col-25">
          <label for="order_amount">Order Amount</label>
        </div>
        <div class="col-75">
          <input type="text" id="order_amount" name="order_amount" >
<!--                 placeholder="Enter Order Amount..">-->
        </div>
      </div>

      <div class="row">
        <div class="col-25">
          <label for="coupon">Promo Code</label>
        </div>
        <div class="col-75">
          <input type="text" id="coupon" name="coupon" >
<!--                 placeholder="Enter Code..">-->
        </div>
      </div>
      <input type="submit" value="Submit">

  </form>
</div>


</body>
</html>